name: Release

on:
  workflow_dispatch:
  push:
    branches:    
      - master
    tags:        
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Changelog
        uses: ardalanamini/auto-changelog@v4
        id  : changelog
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type     : Other Changes
          release-name            : v1.0.0
          release-name-prefix     : ""
          mention-authors         : true
          mention-new-contributors: true
          include-compare-link    : true
          include-pr-links        : true
          include-commit-links    : true
          semver                  : true
          use-github-autolink     : true