name: Release

on:
  workflow_dispatch:
  push:
    branches:    
      - master
    tags:        
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Changelog
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          ACCESS_TOKEN: ${{secrets.GH_TOKEN}}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'

      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        