name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

